name: Fetch GitHub Event Info

on: 
  workflow_dispatch:
      # You can trigger it with other events like pull_request, workflow_dispatch, etc.

jobs:
  fetch-event-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub Event Info
        run: echo "${{ toJson(github.event) }}"
