name: Print ascii key

on:
  push:
    branches:
      - main

jobs:
  ascii:
    runs-on: ubuntu-latest
    steps:
     - name: checkout to repository
       uses: actions/checkout@v4
    
     - name: Exexute shell script
       run: ./script.sh