name: Workflow

on: 
  push:
    branches:
    - main

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout to repository
              uses: actions/checkout@v3

            - name: Print message
              run: | 
                echo "Hello world"
                ls
                cat README.md

            - name: Generate ASCII work
              run: cowsay -f dragon "Run for cover" >> dragon.txt


